language: python
sudo: enabled
python:
    - "3.6"
before_install:
- openssl aes-256-cbc -K $encrypted_8b2a180d1828_key -iv $encrypted_8b2a180d1828_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install google-api-python-client==1.6.6
script:
- python scripts/deploy-funnel.py
- python scripts/premuim-data-funnel.py
- npm install -g data-cli
- data push
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  target-branch: master

env:
  global:
    id: examples
    username: examples
  TRAVIS_SECURE_ENV_VARS: true
